spring.application.name=radarciudadlab


# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/radarciudad_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Upload de CSV de leads
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
